import { useState, useEffect } from 'react';
import Head from 'next/head';
import { Speakers, Logo } from '../components';
import { useTheme } from 'next-themes';

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const { theme, setTheme, resolvedTheme } = useTheme();

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) return null;
  console.log(resolvedTheme);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* TODO: Move hero section to its own component */}
      <div className='flex justify-center py-32 mx-auto'>
        <Logo mode={theme} />
      </div>
      <div className='max-w-6xl mx-auto'>
        <Speakers />
      </div>
    </div>
  );
}
