import Head from 'next/head';
import { Speakers, Hero, Timeline } from '../components';

export default function Home() {
  return (
    <div className='space-y-32'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <div className='max-w-6xl mx-auto space-y-12'>
        <Timeline />
        <Speakers />
      </div>
    </div>
  );
}
